// stack-bench/frontends/astro-solid/src/components/Table.jsx
import {createSignal,createMemo,onMount,For} from 'solid-js';
import {COLS,getN,sortRows,wireCommon,markReady} from '../shared.js';
export default function Table(){const [rows,setRows]=createSignal([]);const [key,setKey]=createSignal('id');const [dir,setDir]=createSignal(1);
onMount(()=>{fetch('/api/rows?n='+getN()).then(r=>r.json()).then(d=>{setRows(d);requestAnimationFrame(()=>markReady());});
wireCommon(ev=>setRows(rs=>rs.map(r=>r.id===ev.row_id?{...r,latency_ms:ev.latency_ms,status:ev.status}:r)));});
const sorted=createMemo(()=>sortRows(rows(),key(),dir()));
return <table><tbody><tr><For each={COLS}>{c=><th onClick={()=>{setDir(key()===c?-dir():1);setKey(c);}}>{c}</th>}</For></tr>
<For each={sorted()}>{r=><tr><For each={COLS}>{c=><td>{String(r[c])}</td>}</For></tr>}</For></tbody></table>;}

// stack-bench/frontends/astro-react/src/components/Table.jsx
import {useState,useEffect,createElement as h} from 'react';
import {COLS,getN,sortRows,wireCommon,markReady} from '../shared.js';
export default function Table(){
  const [rows,setRows]=useState([]);const [key,setKey]=useState('id');const [dir,setDir]=useState(1);
  useEffect(()=>{fetch('/api/rows?n='+getN()).then(r=>r.json()).then(d=>{setRows(d);requestAnimationFrame(()=>markReady());});
    wireCommon(ev=>setRows(rs=>rs.map(r=>r.id===ev.row_id?{...r,latency_ms:ev.latency_ms,status:ev.status}:r)));},[]);
  const sorted=sortRows(rows,key,dir);
  return h('table',null,[h('tbody',{key:'b'},[h('tr',{key:'h'},COLS.map(c=>h('th',{key:c,onClick:()=>{setDir(key===c?-dir:1);setKey(c);}},c))),
    ...sorted.map(r=>h('tr',{key:r.id},COLS.map(c=>h('td',{key:c},String(r[c])))))])]);
}
